### ISSUE TITLE
Inclusion of  System.Collections.Concurrent.ConcurrentDictionary in assembly causes conflicts

### ISSUE THREAD

**Issue by colincnash** [realtime-framework/RealtimeMessaging-Portable#1]
I wish to use this assembly in a PCL containing common logic which I can then reference from my various applications (Xamarin,WPF etc). Unfortunately the inclusion of ConcurrentDictionary under the system namespace conflicts with the Microsoft implimentation on WPF and so my core PCL cannot be referenced. Please can you either not include ConcurrentDictionary or use a different namespace for it.

**Comment by realtime-framework** [comment]
Thanks @colincnash, we'll be looking into it and let you know.

**Comment by realtime-framework** [comment]
@colincnash Let us know if this solves your issue completely.
