### ISSUE TITLE
"Websocket has encountered an error" when connecting on iOS 9

### ISSUE THREAD

**Issue by hkproj** [realtime-framework/RealtimeMessaging-Portable#10]
Hello

I am using, successfully, the following code to connect to Realtime.co using a Windows console application:

```
class Program
{
    public const string ApplicationKey = "XXXX";
    public const string AuthenticationToken = "XXXXX";
    public const string ClusterUrl = "https://ortc-developers.realtime.co/server/ssl/2.1";

    static OrtcClient ortcClient;
    static void Main(string[] args)
    {
        ortcClient = new OrtcClient();
        ortcClient.ClusterUrl = ClusterUrl;
        ortcClient.IsCluster = true;

        ortcClient.OnConnected += OrtcClient_OnConnected;
        ortcClient.OnDisconnected += OrtcClient_OnDisconnected;
        ortcClient.OnSubscribed += OrtcClient_OnSubscribed;
        ortcClient.OnException += OrtcClient_OnException;
        ortcClient.Connect(ApplicationKey, AuthenticationToken);

        Console.ReadLine();
    }

    private static void OrtcClient_OnException(object sender, Exception ex)
    {
        Console.WriteLine("RT: Exception: {0}", ex.Message);
    }

    private static void OrtcClient_OnSubscribed(object sender, string channel)
    {
        Console.WriteLine("RT: Subscribed to {0}", channel);
    }

    private static void OrtcClient_OnDisconnected(object sender)
    {
        Console.WriteLine("RT: Disconnected");
    }

    private static void OrtcClient_OnConnected(object sender)
    {
        Console.WriteLine("RT: Connected");
    }

}
```

However, when using the EXACTLY SAME code on iOS 9, I get "Websocket has encountered an error" as Exception, right after the call to "Connect".
I have added the ATS keys on my Info.plist:

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>facebook.com</key>
    <dict>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSExceptionRequiresForwardSecrecy</key>
      <false/>
    </dict>
    <key>fbcdn.net</key>
    <dict>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSExceptionRequiresForwardSecrecy</key>
      <false/>
    </dict>
    <key>akamaihd.net</key>
    <dict>
      <key>NSIncludesSubdomains</key>
      <true/>
      <key>NSExceptionRequiresForwardSecrecy</key>
      <false/>
    </dict>
  </dict>
</dict>
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>fbapi</string>
  <string>fb-messenger-api</string>
  <string>fbauth2</string>
  <string>fbshareextension</string>
</array>
```

Thank you

**Comment by realtime-framework** [comment]
@hkproj We are looking into this issue and will let you know our findings ASAP.

**Comment by hkproj** [comment]
Using the same code as before, I now get this error: `Unable to get URL from cluster`
I downloaded the library's code to debug it and I have seen that the origin of the problem is the method Balancer.ResolveClusterUrlAsync, which I guess is used to get the URL of the server to connect to.

The exception that gets generated in Balancer.ResolveClusterUrlAsync is System.Net.WebException with the message "Error: SendFailure (Error writing headers)".

**Comment by hkproj** [comment]
I guess you are updating the server, because I now get a different error, which I suppose is caused by an invalid certificate. I attach the call stack. The error is `System.IO.IOException: The authentication or decryption has failed.`
![error](https://cloud.githubusercontent.com/assets/388315/10048967/c0e6fc2a-6215-11e5-96d8-5f2063ae42f4.png)

**Comment by realtime-framework** [comment]
We cannot replicate your issue, so we're inclined to think that maybe your project configured incorrectly. You  must include the nuget packages for all projects. This includes the iOS platform project as well as your PCL forms project. Are you doing that?

If so I guess we'll need you send us a sample project replicating the issue. Please send it to framework@realtime.co

Thanks and sorry for the delay.

PS: I'm closing the issue for now but we'll reopen as soon as we can replicate the issue.

**Comment by realtime-framework** [comment]
Hi @hkproj, with your sample project we were able to replicate the issue. It's related to a limitation on the current Mono TLS implementation. We are trying to find a way of solving it while we wait for a final solution from Mono. You can get more details in the following thread: https://github.com/rdavisau/sockets-for-pcl/issues/35

**Comment by hkproj** [comment]
Hello @realtime-framework, Thank you for your prompt response.

If I remember correctly, disabling certificate validation, **before** making any HTTPS request, solves the problem:
`ServicePointManager.ServerCertificateValidationCallback += (o, certificate, chain, errors) => true;`

Unfortunately, the class ServicePointManager, [is not available](http://stackoverflow.com/a/17780444/739636) in portable libraries, so you can't fix the problem using this code.
Meanwhile I'm trying to create an [Objective-C/Mono binding](https://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/Walkthrough_Binding_objective-c_library/), like most SDKs do.

**Comment by NVentimiglia** [comment]
> Meanwhile I'm trying to create an Objective-C/Mono binding, like most SDKs do.

I will be looking into this today.

**Comment by NVentimiglia** [comment]
Wanted to update on my progress.

1) I Experimented with WebSockets4Net. I was not able to get TLS working there either. I raised the issue with Kerry. https://github.com/kerryjiang/WebSocket4Net

2) I am now trying OKHttp.WS. This uses authobahn / supersocket internally. Again, TLS is not working. mattleibow/square-bindings#4

3) I also tried to make a direct binding with the ibt.ortc android library. Binding projects use code generation to make a bridge library that can access the java classes from c#. The Binding project was not generating any ortc classes at all (but Simple-Json was working fine). Reading the docs this may be related to missing references, but, I included android support and google gcm. There was no exceptions or helpfull output.

**Comment by NVentimiglia** [comment]
I have a prototype working using method 2 and am now working on a release candidate.

**Comment by jparreira** [comment]
Great news

**Comment by hkproj** [comment]
Good news!

I have been working on the binding from Objective-C to Xamarin and I had [some problems](http://forums.xamarin.com/discussion/comment/156524) with the binding tool (Objective Sharpie), but [Xamarin says](http://forums.xamarin.com/discussion/comment/156524/#Comment_156524) that they will be releasing a new version of Objective Sharpie, so I will update you next week on this.

**Comment by NVentimiglia** [comment]
Ok I have a functioning sample for Android and iOS using a new websocket implementation that supports TLS without heachache.

https://github.com/NVentimiglia/Realtime.Messaging.Xamarin

Please test it out

**Comment by jparreira** [comment]
Hi @hkproj, have you tried the new SDK version from https://github.com/NVentimiglia/Realtime.Messaging.Xamarin ?
Please let me know your findings.
Thanks.

**Comment by realtime-framework** [comment]
Due to Mono issues with TLS secure sockets the Portable version of the Xamarin SDK was deprecated. The new Nuget package at https://www.nuget.org/packages/Realtime.Xamarin/ should be used instead.
