### ISSUE TITLE
Error connect websocket

### ISSUE THREAD

**Issue by lcop200685** [realtime-framework/RealtimeMessaging-Portable#3]
Hi

I´m having a problem with your package, It doesn't connect with realtime using pcl library, i did the same test with framework .net and works discarding fails to connection or configuration, the problem is the exception, it doesn't say to much, the message is Websocket has encountered an error, other message is Unable to connect, but it doesn't say me nothing about the real problem, previous to it, appears the following messages

07-29 07:27:08.412 D/Mono    ( 9018): Image addref System.Net.Http[0x5a808960] -> System.Net.Http.dll[0x597b55d0]: 4
07-29 07:27:08.412 D/Mono    ( 9018): Assembly Ref addref WebSocket.Portable.Core[0x58a1d3e0] -> System.Net.Http[0x594da9b8]: 3
07-29 07:27:08.428 D/Mono    ( 9018): Assembly Ref addref WebSocket.Portable.Core[0x58a1d3e0] -> System.Collections[0x577b0ae8]: 3
07-29 07:27:08.436 D/Mono    ( 9018): Assembly Ref addref WebSocket.Portable.Core[0x58a1d3e0] -> System.Globalization[0x589595a8]: 2
07-29 07:27:08.436 D/Mono    ( 9018): Assembly Ref addref System.Globalization[0x589595a8] -> mscorlib[0x40051ec8]: 13
07-29 07:27:08.436 D/Mono    ( 9018): Assembly Ref addref WebSocket.Portable.Core[0x58a1d3e0] -> System.Runtime.Extensions[0x58993830]: 3
07-29 07:27:08.459 D/Mono    ( 9018): Assembly Loader probing location: '/storage/emulated/0/Android/data/RealTimeMessagingAndroid.RealTimeMessagingAndroid/files/.__override__/Sockets.Plugin.dll'.
07-29 07:27:08.459 D/Mono    ( 9018): AOT module '/storage/emulated/0/Android/data/RealTimeMessagingAndroid.RealTimeMessagingAndroid/files/.__override__/Sockets.Plugin.dll.so' not found: dlopen failed: library "/data/app-lib/RealTimeMessagingAndroid.RealTimeMessagingAndroid-1/libaot-Sockets.Plugin.dll.so" not found
07-29 07:27:08.459 D/Mono    ( 9018): AOT module '/Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/Sockets.Plugin.dll.so' not found: dlopen failed: library "/data/app-lib/RealTimeMessagingAndroid.RealTimeMessagingAndroid-1/libaot-Sockets.Plugin.dll.so" not found
07-29 07:27:08.459 D/Mono    ( 9018): Assembly Ref addref WebSocket.Portable.Core[0x58a1d3e0] -> Sockets.Plugin[0x58a28038]: 2
07-29 07:27:08.459 D/Mono    ( 9018): Assembly Ref addref Sockets.Plugin[0x58a28038] -> System.Runtime[0x5898e9b0]: 5
07-29 07:27:08.459 D/Mono    ( 9018): Assembly Ref addref Sockets.Plugin[0x58a28038] -> Sockets.Plugin.Abstractions[0x58a28e90]: 2
07-29 07:27:08.459 D/Mono    ( 9018): Assembly Ref addref Sockets.Plugin.Abstractions[0x58a28e90] -> System.Runtime[0x5898e9b0]: 6
07-29 07:27:08.459 D/Mono    ( 9018): Assembly Ref addref WebSocket.Portable.Core[0x58a1d3e0] -> System.IO[0x5895c3c0]: 2
07-29 07:27:08.459 D/Mono    ( 9018): Assembly Ref addref System.IO[0x5895c3c0] -> mscorlib[0x40051ec8]: 14
07-29 07:27:08.467 D/Mono    ( 9018): Assembly Ref addref Sockets.Plugin[0x58a28038] -> System.Threading.Tasks[0x589fb0a8]: 4
07-29 07:27:08.467 D/Mono    ( 9018): Assembly Ref addref Sockets.Plugin.Abstractions[0x58a28e90] -> System.Threading.Tasks[0x589fb0a8]: 5
07-29 07:27:08.467 D/Mono    ( 9018): Assembly Ref addref Sockets.Plugin[0x58a28038] -> System.IO[0x5895c3c0]: 3
07-29 07:27:08.467 D/Mono    ( 9018): Assembly Ref addref Sockets.Plugin.Abstractions[0x58a28e90] -> System.IO[0x5895c3c0]: 4
07-29 07:27:08.467 D/Mono    ( 9018): Assembly Ref addref Sockets.Plugin[0x58a28038] -> System.Resources.ResourceManager[0x5898bb90]: 5
07-29 07:27:08.475 D/Mono    ( 9018): Assembly Loader probing location: '/storage/emulated/0/Android/data/RealTimeMessagingAndroid.RealTimeMessagingAndroid/files/.__override__/System.Net.Requests.dll'.
07-29 07:27:08.475 D/Mono    ( 9018): AOT module '/storage/emulated/0/Android/data/RealTimeMessagingAndroid.RealTimeMessagingAndroid/files/.__override__/System.Net.Requests.dll.so' not found: dlopen failed: library "/data/app-lib/RealTimeMessagingAndroid.RealTimeMessagingAndroid-1/libaot-System.Net.Requests.dll.so" not found
07-29 07:27:08.483 D/Mono    ( 9018): AOT module '/Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/System.Net.Requests.dll.so' not found: dlopen failed: library "/data/app-lib/RealTimeMessagingAndroid.RealTimeMessagingAndroid-1/libaot-System.Net.Requests.dll.so" not found
07-29 07:27:08.483 D/Mono    ( 9018): Assembly Ref addref WebSocket.Portable.Core[0x58a1d3e0] -> System.Net.Requests[0x589738c0]: 2

I'm using xamarin PCL Library with android, and I'm agree with your help thanks

**Comment by realtime-framework** [comment]
the problem was i was using url port single and not web secure http protocol "https", In the example of realtime the url http is simple, but in the example of the NVentimiglia, He uses https, it shouldn't be problem, but it was my solution, thanks Joao, it's the answer

El miércoles, 29 de julio de 2015, 9:28:24 (UTC-5), João Parreira escribió:

    Have you tried connecting using a secure connection? Use the following cluster url (note the /ssl in the path):

    https://ortc-developers.realtime.co/server/ssl/2.1

    Maybe something in your network is blocking the websocket protocol (encrypted connections generally help when this happens).
